config/routes.rb
Rails.application.routes.draw do
  root to: "public/homes#top"

  namespace :admin do
    resources :customers, only:[:index,:show,:edit,:update]
    resources :items, only:[:new, :index,:show,:edit,:update,:create]
    resources :orders, only:[:show]
    root to: 'homes#top'
  end

  scope module: :public do
    resources :items, only: [:index, :show]
    delete 'cart_items/destroy_all', to: 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    get 'orders/thanks', to: 'orders#thanks'
    resources :orders, only: [:index, :show, :new, :create]
    #resources :customers, only: [:show, :edit, :withdrawal]
    # routes.rb
    post 'orders/check', to: 'orders#check'
    get 'customers/my_page', to: 'customers#show' ,as: :my_page
    get '/customers/information/edit', to: 'customers#edit', as: :customers_edit
    patch '/customers/information', to: 'customers#update'
    patch '/customers/quit', to: 'customers#quit'
    get 'customers/withdrawal'
    get "/about" => "homes#about", as: "about"
  end
 # 顧客用
# URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

# 管理者用
# URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
  #validates :password_confirmation, presence: true

  def active_for_authentication?
    super && (is_deleted == false)
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers =Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end


  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice] = "会員情報を更新しました."
      redirect_to admin_customer_path(@customer)
    else
      flash[:notice] = "会員の更新に失敗しました."
      render :edit
    end
  end


  private

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number,:email, :password, :is_deleted)
  end

  def authenticate_admin!
    unless admin_signed_in?  # Devise提供のヘルパー
      redirect_to root_path
    end
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<p id="notice"></p>
<div>
  <%= flash[:notice] %>
</div>
<% if @customer.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-10 col-lg-10 px-5 py-5 px-sm-0 ">
      <div class="form-group row">
        <span class="bg-light px-2 h4 mb-3"><%= "#{@customer.last_name}#{@customer.first_name}" %>さんの会員情報編集</span>
      </div>
      <%= form_with model: [:admin, @customer] do |f| %>
      <div class="form-group row"> <!-- こちらの全角スペースを削除しました -->
          <label class="col-3 col-form-label">会員ID</label>
          <div class="col-4">
            <%= @customer.id %>
          </div>
      </div>
      <div class="form-group row"> <!-- こちらの全角スペースを削除しました -->
          <label class="col-3 col-form-label">氏名</label>
          <div class="col-4">
            <%= f.text_field :last_name, class:"form-control", id:"inputLastName" %>
          </div>
          <div class="col-4">
            <%= f.text_field :first_name, class:"form-control", id:"inputFirstName"%>
          </div>
      </div>
        <div class="form-group row">
          <label class="col-3 col-form-label">フリガナ</label>
          <div class="col-4">
            <%= f.text_field :last_name_kana, class:"form-control", id:"inputLastNameKana" %>
          </div>
          <div class="col-4">
            <%= f.text_field :first_name_kana, class:"form-control", id:"inputFirstNameKana"%>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-3 col-form-label">郵便番号</label>
          <div class="col-4">
            <%= f.text_field :postal_code, class:"form-control", id:"inputPostalCode" %>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-3 col-form-label">住所</label>
          <div class="col-9">
            <%= f.text_field :address, class:"form-control", id:"inputAddress" %>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-3 col-form-label">電話番号</label>
          <div class="col-4">
            <%= f.text_field :telephone_number, class:"form-control", id:"inputTelephoneNumber" %>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-3 col-form-label">メールアドレス</label>
          <div class="col-4">
            <%= f.text_field :email, class:"form-control", id:"inputEmail" %>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-3 col-form-label">会員ステータス</label>
          <div class="col-4">
            <%= f.radio_button :is_deleted, :false %>
            <%= f.label :is_deleted, "有効", { value: :false }  %>

            <%= f.radio_button :is_deleted, :true %>
            <%= f.label :is_deleted, "退会", { value: :true } %>
          </div>
        </div>
        <div class="form-group row text-center">
          <div class="col-4">
            <%= f.submit "編集内容を保存", class:"btn btn-success" %>
          </div>
        </div>
      <% end %>
  　</div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-12 col-md-8 col-lg-8 px-5 py-5 px-sm-0 ">
      <span class="bg-light px-2 h4">会員一覧</span>
      <table class="table mt-4 border-bottom">
        <thead>
          <tr>
            <th class="bg-light">会員ID</th>
            <th class="bg-light">氏名</th>
            <th class="bg-light">メールアドレス</th>
            <th class="bg-light">ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
            <tr>
              <td><%= customer.id %></td>
              <td><%= link_to "#{customer.last_name} #{customer.first_name}" , admin_customer_path(customer.id), class: "text-dark text-decoration-underline"%></td>
              <td><%= customer.email %></td>
              <td>
                <% if !customer.is_deleted %>
                <span class="text-success font-weight-bold">有効</span>
                <% else %>
                <span class="text-muted font-weight-bold">退会</span>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="field row mt-4 d-flex justify-content-center">
        <div class="d-inline-block mx-auto">
          <%= paginate @customers %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<p id="notice"></p>
<div>
  <%= flash[:notice] %>
</div>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-10 col-lg-10 px-5 py-5 px-sm-0 ">
      <div class="form-group row">
        <span class="bg-light px-2 h4 mb-3"><%= "#{@customer.last_name}#{@customer.first_name}" %>さんの会員詳細</span>
      </div>
      <div class="form-group row"> <!-- こちらの全角スペースを削除しました -->
          <label class="col-3 col-form-label">会員ID</label>
          <div class="col-4">
            <%= @customer.id %>
          </div>
      </div>
      <div class="form-group row"> <!-- こちらの全角スペースを削除しました -->
          <label class="col-3 col-form-label">氏名</label>
          <div class="col-6">
            <%= "#{@customer.last_name} #{@customer.first_name}" %>
          </div>
      </div>
        <div class="form-group row">
          <label class="col-3 col-form-label">フリガナ</label>
          <div class="col-8">
            <%= "#{@customer.last_name_kana} #{@customer.first_name_kana}" %>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-3 col-form-label">郵便番号</label>
          <div class="col-4">
            <%= @customer.postal_code %>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-3 col-form-label">住所</label>
          <div class="col-9">
            <%= @customer.address %>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-3 col-form-label">電話番号</label>
          <div class="col-4">
            <%= @customer.telephone_number %>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-3 col-form-label">メールアドレス</label>
          <div class="col-4">
            <%= @customer.email %>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-3 col-form-label">会員ステータス</label>
          <div class="col-4">
            <% if !@customer.is_deleted %>
            <span class="text-success font-weight-bold">有効</span>
            <% else %>
            <span class="text-muted font-weight-bold">退会</span>
            <% end %>
          </div>
        </div>
        <div class="form-group row text-center">
          <div class="col-4">
            <a href="<%= edit_admin_customer_path %>" class="btn btn-success">編集する</a>
          </div>
          <div class="col-4">
            <a href="<%= admin_root_path %>" class="btn btn-primary">注文履歴一覧を見る</a>
          </div>
        </div>
  　</div>
  </div>
</div>