config/routes.rb
Rails.application.routes.draw do
  root to: "public/homes#top"

  namespace :admin do
    resources :customers, only:[:index,:show,:edit,:update]
    resources :items, only:[:new, :index,:show,:edit,:update,:create]
    resources :orders, only:[:show]
    root to: 'homes#top'
  end

  scope module: :public do
    resources :items, only: [:index, :show]
    delete 'cart_items/destroy_all', to: 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    get 'orders/thanks', to: 'orders#thanks'
    resources :orders, only: [:index, :show, :new, :create]
    #resources :customers, only: [:show, :edit, :withdrawal]
    # routes.rb
    post 'orders/check', to: 'orders#check'
    get 'customers/my_page', to: 'customers#show' ,as: :my_page
    get '/customers/information/edit', to: 'customers#edit', as: :customers_edit
    patch '/customers/information', to: 'customers#update'
    patch '/customers/quit', to: 'customers#quit'
    get 'customers/withdrawal'
    get "/about" => "homes#about", as: "about"
  end
 # 顧客用
# URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

# 管理者用
# URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  enum payment_method: { credit_card: 0, transfer: 1 }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  def show
    @order = Order.find(params[:id])
    @total_price = @order.total_price
  end

  private

  def authenticate_admin!
    unless admin_signed_in?  # Devise提供のヘルパー
      redirect_to root_path
    end
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 mt-4">
      <span class="bg-light px-2 h4 mb-3">注文履歴詳細</span>
      <div class="form-group row mt-4"> <!-- こちらの全角スペースを削除しました -->
        <label class="col-3 col-form-label font-weight-bold">購入者</label>
        <div class="col-6">
          <%= link_to "#{@order.customer.last_name} #{@order.customer.first_name}", admin_customer_path(@order.customer), class: "text-dark text-decoration-underline" %>
        </div>
      </div>
      <div class="form-group row">
        <label class="col-3 col-form-label font-weight-bold">注文日</label>
        <div class="col-4">
          <%= @order.created_at.strftime('%Y/%m/%d') %>
        </div>
      </div>
      <div class="form-group row">
        <label class="col-3 col-form-label font-weight-bold">住所</label>
        <div class="col-9">
          <p>〒<%= @order.postal_code %><%= @order.address %></p>
          <p><%= @order.name %></p>
        </div>
      </div>
      <div class="form-group row">
        <label class="col-3 col-form-label font-weight-bold">支払い方法</label>
        <div class="col-4">
          <%= Order.payment_methods_i18n[@order.payment_method.to_sym] %>
        </div>
      </div>
      <div class="row mt-4">
        <div class="col-md-8">
          <table class="table table-bordered">
            <thead class="bg-light">
              <tr>
                <th>商品名</th>
                <th>単価（税込）</th>
                <th>数量</th>
                <th>小計</th>
              </tr>
            </thead>
            <tbody>
              <% @order.order_details.each do |detail| %>
                <tr>
                  <td><%= detail.item.name %></td>
                  <td>¥<%= number_with_delimiter(tax_included_price(detail.item.price)) %></td>
                  <td><%= detail.amount %></td>
                  <td>¥<%= number_with_delimiter(tax_included_price(detail.item.price * detail.amount)) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>

        <div class="col-md-4 mt-5">
          <div class="d-flex flex-column h-100"> <!-- 縦方向の高さを最大に -->
          　<div class="mt-auto">  <!-- 縦方向の最後に配置 -->
            　<table class="table">
              　<tbody>
                　<tr>
                  　<td class="h4 font-weight-bold">商品合計</td>
                  　<td class="h4 text-end">¥<%= number_with_delimiter(@total_price - @order.postage) %></td> <!-- 右寄せ -->
                　</tr>
                　<tr>
                  　<td class="h4 font-weight-bold">送料</td>
                  　<td class="h4 text-end">¥<%= number_with_delimiter(@order.postage) %></td> <!-- 右寄せ -->
                　</tr>
                　<tr>
                  　<td class="h4 font-weight-bold">請求金額合計</td>
                  　<td class="h4 text-end">¥<%= number_with_delimiter(@total_price) %></td> <!-- 右寄せ -->
                　</tr>
              　</tbody>
            　</table>
          　</div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>