config/routes.rb
Rails.application.routes.draw do
  root to: "public/homes#top"

  namespace :admin do
    resources :customers, only:[:index,:show,:edit,:update]
    resources :items, only:[:new, :index,:show,:edit,:update,:create]
    resources :orders, only:[:show]
    root to: 'homes#top'
  end

  scope module: :public do
    resources :items, only: [:index, :show]
    delete 'cart_items/destroy_all', to: 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    get 'orders/thanks', to: 'orders#thanks'
    resources :orders, only: [:index, :show, :new, :create]
    #resources :customers, only: [:show, :edit, :withdrawal]
    # routes.rb
    post 'orders/check', to: 'orders#check'
    get 'customers/my_page', to: 'customers#show' ,as: :my_page
    get '/customers/information/edit', to: 'customers#edit', as: :customers_edit
    patch '/customers/information', to: 'customers#update'
    patch '/customers/quit', to: 'customers#quit'
    get 'customers/withdrawal'
    get "/about" => "homes#about", as: "about"
  end
 # 顧客用
# URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

# 管理者用
# URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/ff6b815b69.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
          <a class="navbar-brand" href="/"><%= image_tag "logo-black.png", alt: "Nagano Cake", width: "120" %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if customer_signed_in? %>
                <!-- For Customers -->
                <li class="nav-item">
                  <%= link_to 'マイページ', my_page_path, class: "nav-link text-dark bordered-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to '商品一覧', items_path, class: "nav-link text-dark bordered-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to 'カート', cart_items_path, class: "nav-link text-dark bordered-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "nav-link text-dark bordered-link" %>
                </li>
              <% elsif admin_signed_in? %>
                <!-- For Admins -->
                <li class="nav-item">
                  <%= link_to '商品一覧', admin_items_path, class: "nav-link text-dark bordered-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to '会員一覧', admin_customers_path, class: "nav-link text-dark bordered-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to '注文履歴一覧', admin_root_path, class: "nav-link text-dark bordered-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link text-dark bordered-link" %>
                </li>
              <% else %>
                <!-- For Non-Logged-In Users -->
                <li class="nav-item">
                  <%= link_to "About", about_path, class: "nav-link text-dark bordered-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "商品一覧", items_path, class: "nav-link text-dark bordered-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "新規登録", new_customer_registration_path, class: "nav-link text-dark bordered-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログイン", new_customer_session_path, class: "nav-link text-dark bordered-link" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>